/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package template

import com.kotlindiscord.kord.extensions.ExtensibleBot
import com.kotlindiscord.kord.extensions.utils.env
import dev.kord.common.entity.Snowflake
import dev.kord.gateway.Intent
import dev.kord.gateway.Intents
import dev.kord.gateway.PrivilegedIntent
import template.extensions.*

val TEST_SERVER_ID = Snowflake(
    env("TEST_SERVER")  // Get the test server ID from the env vars or a .env file
)

private val TOKEN = env("BOT_TOKEN")   // Get the bot' token from the env vars or a .env file

@OptIn(PrivilegedIntent::class)
suspend fun main() {
    val bot = ExtensibleBot(TOKEN) {
        extensions {
            add(::EightBallExtension)
            add(::FilteredChannelExtension)
            add(::MonitorExtension)
            add(::StatusExtension)
            add(::NSFWImageExtension)
            add(::SFWImageExtension)
        }

        presence { playing("haha ball") }

        intents {
            +Intents.nonPrivileged
            +Intent.MessageContent
        }
    }

    bot.start()
}
